apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  rules:
  - host: apple.com                 # Assign host name to IP add in /etc/hosts file
    http:                         # echo " 192.168.0.5 domain.com" >> /etc/hosts
      paths:
      - pathType: Prefix
        path: "/"                   # name based routing  
        backend:
          service:
            name: my-svc-home 
            port: 
              number: 80
  - host: apple.com/mobile
    http:
      paths:
      - pathType: Prefix
        path: "/mobile"
        backend:
          service:
            name: my-svc-mobile
            port: 
              number: 80
