apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  rules:
  - host: apple.com                 
    http:                         
      paths:
      - pathType: Prefix
        path: "/"                     
        backend:
          service:
            name: my-svc-home 
            port: 
              number: 80
      path:        
      - pathType: pre
  # - host: apple.com.mobile
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: "/mobile"
  #       backend:
  #         service:
  #           name: my-svc-mobile
  #           port: 
  #             number: 80
