apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp
    env: devops
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: http
          containerPort: 80
---



