apiVersion: v1
kind: Service
metadata:
  name: my-svc-node
  labels:
    app: my-svc-node
    env: devops
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
