- name: install packages
  hosts: all
  tasks:
    - name: install httpd
      yum:
       name: httpd
       state: latest
       when: 
    - name: install apache2
      apt:
       name: apache2
       state: latest

