- name: using loop module
  hosts: all
  tasks:
    - name: print all fruits
      debug:
        msg: "{{item}}"
      loop:
        - apple
        - banana
        - mango
    - name: install apache2
      package: 
       name: "{{item}}"
       state: latest
    