- name: using package module
  hosts: all
  tasks:
    - name: install httpd
      package:
       name: httpd
       state: latest
      when: ansible_os_family == "RedHat"
    - name: install apache2
      package: 
       name: apache2
       state: latest
      when: ansible_os_family == "Debian"
    - name: start service
      systemd_service:
       name: start service
       state: restarted
       enabled: true
       daemon_reload: true


