- name: my sample playbook
  hosts: all
  vars: 
    city: "pune"
  tasks: 
  - name: 1st-msg
    debug:
      msg: "welcome to "{{ city }}"
  - name: 2st-msg
    debug:
      msg: "welcome to devops"
  - name: 3st-msg
    debug:
      msg: "welcome to india"