apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mybinding
subjects:
- kind: User
  name: ironman
  apiGroup: rbac.authorization.k8s.io

roleRef:
 kind: Role
 name: myrole
 apiGroup: rbac.authorization.k8s.io
